version: '2'

services:
  ui:
    image: hypriot/rpi-dockerui
    container_name: docker-ui
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    expose:
      - 9000
    ports:
      - 80:9000

  web:
    image: johncclayton/electric-pi-web${VERSION_TAG}

    container_name: electric-web
    command: sh -x /www/run_gunicorn.sh

    environment:
      - ELECTRIC_WORKER=tcp://worker:5001

    ports:
      - 5000:5000

    restart: always

    depends_on:
      - worker

  worker:
    image: johncclayton/electric-pi-worker${VERSION_TAG}

    container_name: electric-worker
    command: sh -x /www/run_zmq_worker.sh
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /opt/prefs:/opt/prefs

    restart: always

